[package]
name = "magneto_optical_trap"
version = "0.1.0"
authors = ["Pi-sun <37469116+Pi-sun@users.noreply.github.com>"]
edition = "2018"

[dependencies]
specs="0.14.0"
specs-derive = "0.4.0"
rand = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8.9"
assert_approx_eq = "1.1.0"
nalgebra = { version = "0.18", features = ["serde-serialize"] }
csv = "1.1"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 16
panic = 'unwind'
incremental = false
overflow-checks = false