[package]
name = "magneto_optical_trap"
version = "0.1.0"
authors = ["Pi-sun <37469116+Pi-sun@users.noreply.github.com>"]
edition = "2018"

[dependencies]
specs="0.14.0"
specs-derive = "0.4.0"
rand = "0.4.0"
kiss3d = "0.8.0"
nalgebra = "0.16"
yaml-rust = "0.4"